
export const trashItems = [
    {
        id: "Aluminum-Can",
        name: "Aluminum Can",
        bin: "Recycling",
        co2e: 170,
    },
    {
        id: "Aluminum-Foil",
        name: "Aluminum Foil",
        bin: "Recycling",
        note: "Please rinse and flatten",
        co2e: 10,
    },
    {
        id: "Bio-Plastic-Cup",
        name: "Bio-Plastic Cup",
        bin: "Compost",
        co2e: 70,
    },
    {
        id: "Cardboard",
        name: "Cardboard",
        bin: "Recycling",
        note: "Please flatten all cardboard",
        co2e: 80,
    },
    {
        id: "Food",
        name: "Food",
        bin: "Compost",
        co2e: 1000,
    },
    {
        id: "Food-Wrapper",
        name: "Food Wrapper",
        bin: "Landfill",
        co2e: 6,
    },
    {
        id: "Paper",
        name: "Paper",
        bin: "Recycling",
        co2e: 8,
    },
    {
        id: "Paper-Cup",
        name: "Paper Cup",
        bin: "Recycling",
        co2e: 11,
    },
    {
        id: "Paper-Plate",
        name: "Paper Plate",
        bin: "Compost",
        co2e: 15,
    },
    {
        id: "Paper-Soft",
        name: "Soft Paper",
        bin: "Recycling",
        co2e: 5,
    },
    {
        id: "Plastic-Bag",
        name: "Plastic Bag",
        bin: "Landfill",
        co2e: 33,
    },
    {
        id: "Plastic-Bottle",
        name: "Plastic Bottle",
        bin: "Recycling",
        note: "Only hard number 1 or 2 bottles",
        co2e: 82,
    },
    {
        id: "Plastic-Container",
        name: "Plastic Container",
        bin: "Recycling",
        note: "Only hard plastics number 1 or 2",
        co2e: 100,
    },
    {
        id: "Plastic-Cup",
        name: "Plastic Cup",
        bin: "Recycling",
        note: "Only hard plastics number 1 or 2",
        co2e: 30,
    },
    {
        id: "Plastic-Utensil",
        name: "Plastic Utensil",
        bin: "Landfill",
        co2e: 8,
    },
    {
        id: "Styrofoam",
        name: "Styrofoam",
        bin: "Landfill",
        co2e: 45,
    },
];